services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mono
      POSTGRES_PASSWORD: mono_dev
      POSTGRES_DB: jwt_auth
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

